SELECT H.HACKER_ID, NAME, SUM(SCR) AS TOTAL
FROM HACKERS H
JOIN (SELECT HACKER_ID, MAX(SCORE) AS SCR
      FROM SUBMISSIONS
      GROUP BY HACKER_ID, CHALLENGE_ID
     ) AS MAXSCORE
     ON H.HACKER_ID = MAXSCORE.HACKER_ID
GROUP BY H.HACKER_ID, NAME
HAVING TOTAL > 0
ORDER BY TOTAL DESC, H.HACKER_ID
