SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W 
JOIN WANDS_PROPERTY P ON W.CODE = P.CODE
JOIN (SELECT W.POWER, MIN(W.COINS_NEEDED) AS MINCOINS, P.AGE
      FROM WANDS W
      JOIN WANDS_PROPERTY P ON W.CODE = P.CODE
      WHERE IS_EVIL = 0
      GROUP BY W.POWER, P.AGE) AS MINS
      ON MINS.AGE = P.AGE AND MINS.POWER = W.POWER AND W.COINS_NEEDED = MINS.MINCOINS
WHERE P.IS_EVIL = 0
ORDER BY W.POWER DESC, P.AGE DESC
