SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') AS NEWNAME
FROM OCCUPATIONS
ORDER BY NEWNAME;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION), 's.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION);
