/* SELECT SALARY * MONTHS AS EARNINGS, COUNT(*)
FROM EMPLOYEE
WHERE SALARY * MONTHS = (SELECT MAX(SALARY * MONTHS) AS MAXSALARY
      FROM EMPLOYEE)
GROUP BY EARNINGS */
SELECT SALARY * MONTHS AS EARNINGS, COUNT(*)
FROM EMPLOYEE
GROUP BY EARNINGS
ORDER BY EARNINGS DESC LIMIT 1
