/*1. IF 20,20 ONLY APPEARS ONE TIME, IT SHOULD NOT BE RETURNED
  2. ONLY RETURN 2,24 NOT 2,24 AND 24,2. POOR DESCRIPTION!*/
SELECT X, Y
FROM FUNCTIONS F1
WHERE EXISTS (SELECT * 
             FROM FUNCTIONS F2
             WHERE F1.X = F2.Y AND F1.Y = F2.X AND F1.X < F2.X) AND X != Y
UNION
SELECT X, Y
FROM FUNCTIONS F1
WHERE X = Y AND (SELECT COUNT(*)
                 FROM FUNCTIONS F2
                 WHERE F1.X = F2.X AND F1.Y = F2.Y) > 1
ORDER BY X
